"""Trains one UNet specialized for a single noise level. Run once per noise level:
python -m src.methods.end2end_unet.train_unet --noise_level 0.01

Training images are degraded on the fly (fixed blur, fixed noise level, fresh noise
draw every epoch) so the noise realization acts as implicit augmentation. Validation
uses the fixed dev set already generated by generate_degraded_sets.py -- same images,
never touched during training, so the reported dev PSNR is a fair checkpoint signal."""
import argparse
import glob
import os

import torch
import torch.nn as nn
from PIL import Image
from torch.utils.data import Dataset, DataLoader
from torchvision.transforms.functional import to_tensor

from src.data.kaokore import KaokoreDataset
from src.degradation.operators import Blurring
from src.eval.metrics import psnr
from src.methods.end2end_unet.model import UNet
from src.utils.device import get_device


class OnTheFlyDataset(Dataset):
    def __init__(self, root: str, noise_level: float, n_images: int, image_size: int = 256):
        self.base = KaokoreDataset(root, split="train", image_size=image_size)
        g = torch.Generator().manual_seed(0)
        keep = torch.randperm(len(self.base), generator=g)[:n_images].tolist()
        self.base.entries = [self.base.entries[i] for i in keep]
        self.blur = Blurring(channels=3, kernel_size=9, sigma=2.0)
        self.noise_level = noise_level

    def __len__(self):
        return len(self.base)

    def __getitem__(self, index):
        x, _ = self.base[index]
        y = self.blur._matvec(x.unsqueeze(0))[0] + torch.randn_like(x) * self.noise_level
        return x, y


def load_dev_set(level: float):
    clean_dir = "data/degraded/dev/clean"
    deg_dir = f"data/degraded/dev/sigma_{level}"
    names = sorted(os.path.basename(p) for p in glob.glob(os.path.join(clean_dir, "*.jpg")))
    pairs = []
    for name in names:
        x = to_tensor(Image.open(os.path.join(clean_dir, name)).convert("RGB"))
        y = to_tensor(Image.open(os.path.join(deg_dir, name)).convert("RGB"))
        pairs.append((x, y))
    return pairs


def run(noise_level: float, n_images: int, epochs: int, batch_size: int, lr: float):
    device = get_device()
    print(f"device: {device}")

    dataset = OnTheFlyDataset("data/kaokore", noise_level, n_images)
    loader = DataLoader(dataset, batch_size=batch_size, shuffle=True)
    dev_pairs = load_dev_set(noise_level)

    model = UNet().to(device)
    opt = torch.optim.Adam(model.parameters(), lr=lr)
    loss_fn = nn.L1Loss()

    os.makedirs("results/checkpoints", exist_ok=True)
    ckpt_path = f"results/checkpoints/unet_sigma_{noise_level}.pt"
    best_psnr = -1.0

    for epoch in range(epochs):
        model.train()
        total_loss = 0.0
        for x, y in loader:
            x, y = x.to(device), y.to(device)
            opt.zero_grad()
            pred = model(y)
            loss = loss_fn(pred, x)
            loss.backward()
            opt.step()
            total_loss += loss.item() * x.size(0)
        train_loss = total_loss / len(dataset)

        model.eval()
        with torch.no_grad():
            scores = [
                psnr(model(y.unsqueeze(0).to(device)).clamp(0, 1).cpu()[0], x)
                for x, y in dev_pairs
            ]
        dev_psnr = sum(scores) / len(scores)
        print(f"epoch {epoch+1}/{epochs} loss={train_loss:.4f} dev_psnr={dev_psnr:.3f}")

        if dev_psnr > best_psnr:
            best_psnr = dev_psnr
            torch.save(model.state_dict(), ckpt_path)

    print(f"best dev psnr for sigma={noise_level}: {best_psnr:.3f} -> saved to {ckpt_path}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--noise_level", type=float, required=True)
    parser.add_argument("--n_images", type=int, default=1000)
    parser.add_argument("--epochs", type=int, default=20)
    parser.add_argument("--batch_size", type=int, default=8)
    parser.add_argument("--lr", type=float, default=2e-4)
    args = parser.parse_args()
    run(args.noise_level, args.n_images, args.epochs, args.batch_size, args.lr)
